// Auto-generated from ha_entities.csv export. Edit this file directly to
// rename, regroup, relocate, or add/remove entities from Smart Home.
export const SMART_HOME_ENTITIES = [
  { id: "binary_sensor.firewalla_wan_status", name: "Firewalla WAN status", section: "Network Backend", group: "Firewalla", location: "Loft", color: false },
  { id: "camera.cottage_view", name: "Cottage View", section: "Cameras", group: "Outdoor Cameras", location: "Cottage", color: false },
  { id: "camera.deck_view", name: "Deck View", section: "Cameras", group: "Outdoor Cameras", location: "Deck", color: false },
  { id: "camera.driveway_view", name: "Driveway View", section: "Cameras", group: "Outdoor Cameras", location: "Driveway", color: false },
  { id: "camera.entry_way_doorbell", name: "Entry way doorbell", section: "Cameras", group: "Outdoor Cameras", location: "Entryway", color: false },
  { id: "camera.house_right_side_view", name: "House Right Side View", section: "Cameras", group: "Outdoor Cameras", location: "House", color: false },
  { id: "camera.living_room_camera", name: "Living Room Camera", section: "Cameras", group: "Indoor Camera", location: "Living Room", color: false },
  { id: "camera.loft_camera", name: "Loft camera", section: "Cameras", group: "Indoor Camera", location: "Loft", color: false },
  { id: "camera.patio_view", name: "Patio View", section: "Cameras", group: "Indoor Camera", location: "Patio", color: false },
  { id: "camera.rec_room_door_view", name: "Rec Room Door View", section: "Cameras", group: "Outdoor Cameras", location: "Rec Room", color: false },
  { id: "camera.rec_room_indoor_camera", name: "Rec Room Indoor Camera", section: "Cameras", group: "Indoor Camera", location: "Rec Room", color: false },
  { id: "climate.hallway_hallway", name: "Hallway", section: "Climate", group: "Thermostat", location: "Hallway", color: false },
  { id: "event.cottage_view_motion", name: "Cottage View Motion", section: "Cameras", group: "Outdoor Cameras", location: "Cottage", color: false },
  { id: "event.deck_view_motion", name: "Deck View Motion", section: "Cameras", group: "Outdoor Cameras", location: "Deck", color: false },
  { id: "event.driveway_view_motion", name: "Driveway View Motion", section: "Cameras", group: "Outdoor Cameras", location: "Driveway", color: false },
  { id: "event.entry_way_doorbell_chime", name: "Entry way doorbell Chime", section: "Cameras", group: "Outdoor Cameras", location: "Entryway", color: false },
  { id: "event.house_right_side_view_motion", name: "House Right Side View Motion", section: "Cameras", group: "Outdoor Cameras", location: "House", color: false },
  { id: "event.living_room_camera_motion", name: "Living Room Camera Motion", section: "Cameras", group: "Indoor Camera", location: "Living Room", color: false },
  { id: "event.loft_camera_motion", name: "Loft camera Motion", section: "Cameras", group: "Indoor Camera", location: "Loft", color: false },
  { id: "event.patio_view_motion", name: "Patio View Motion", section: "Cameras", group: "Outdoor Cameras", location: "Patio", color: false },
  { id: "event.rec_room_door_view_motion", name: "Rec Room Door View Motion", section: "Cameras", group: "Outdoor Cameras", location: "Rec Room", color: false },
  { id: "event.rec_room_indoor_camera_motion", name: "Rec Room Indoor Camera Motion", section: "Cameras", group: "Indoor Camera", location: "Rec Room", color: false },
  { id: "light.back_fan_bulb_1", name: "Back Fan Bulb 1", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.back_fan_bulb_2", name: "Back Fan Bulb 2", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.back_fan_bulb_3", name: "Back Fan Bulb 3", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.back_fan_bulb_4", name: "Back Fan Bulb 4", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.back_rec_room_fan", name: "Back Rec Room Fan", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.deck_lights", name: "Deck Lights", section: "Lights", group: "Outdoor Lights", location: "Deck", color: true },
  { id: "light.deck_stairs", name: "Deck Stairs", section: "Lights", group: "Outdoor Lights", location: "Deck", color: true },
  { id: "light.dog_closet", name: "Dog Closet", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.fireplace_light", name: "Fireplace Light", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.flood_lights", name: "Flood Lights", section: "Lights", group: "Outdoor Lights", location: "Backyard", color: true },
  { id: "light.fridge_1", name: "Fridge 1", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.fridge_2", name: "Fridge 2", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.fridge_3", name: "Fridge 3", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.fridge_lights", name: "Fridge Lights", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.front_fan_bulb_1", name: "Front Fan Bulb 1", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.front_fan_bulb_2", name: "Front Fan Bulb 2", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.front_fan_bulb_3", name: "Front Fan Bulb 3", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.front_fan_bulb_4", name: "Front Fan Bulb 4", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.front_porch_light_1", name: "Front Porch Light 1", section: "Lights", group: "Outdoor Lights", location: "Entryway", color: true },
  { id: "light.front_porch_light_2", name: "Front Porch Light 2", section: "Lights", group: "Outdoor Lights", location: "Entryway", color: true },
  { id: "light.front_rec_room_fan", name: "Front Rec Room Fan", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.grill_lights", name: "Grill Lights", section: "Lights", group: "Outdoor Lights", location: "Patio", color: true },
  { id: "light.h6076_173d", name: "Left Floor Lamp", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.h7066_3337", name: "Spotlights Right", section: "Lights", group: "Outdoor Lights", location: "Frontyard", color: true },
  { id: "light.h7066_345b", name: "Spotlights Left", section: "Lights", group: "Outdoor Lights", location: "Frontyard", color: true },
  { id: "light.h70b5_7255", name: "Curtain Lights", section: "Lights", group: "Outdoor Lights", location: "Frontyard", color: true },
  { id: "light.lucas_light", name: "Lucas Light", section: "Lights", group: "Indoor Lights", location: "Lucas's Room", color: true },
  { id: "light.porch_light_1", name: "Porch Light 1", section: "Lights", group: "Outdoor Lights", location: "Porch", color: true },
  { id: "light.porch_light_2", name: "Porch Light 2", section: "Lights", group: "Outdoor Lights", location: "Porch", color: true },
  { id: "light.porch_light_4", name: "Porch Light 4", section: "Lights", group: "Outdoor Lights", location: "Porch", color: true },
  { id: "light.porch_light_5", name: "Porch Light 5", section: "Lights", group: "Outdoor Lights", location: "Porch", color: true },
  { id: "light.porch_light_7", name: "Porch Light 7", section: "Lights", group: "Outdoor Lights", location: "Porch", color: true },
  { id: "light.porch_light_8", name: "Porch Light 8", section: "Lights", group: "Outdoor Lights", location: "Porch", color: true },
  { id: "light.rec_room_floor_lamps", name: "Rec Room Floor Lamps", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.rec_room_fridge_lights", name: "Rec Room Fridge Lights", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.right_floor_lamp", name: "Right Floor Lamp", section: "Lights", group: "Indoor Lights", location: "Rec Room", color: true },
  { id: "light.tyler_s_air_purifier", name: "Tyler's Air Purifier", section: "Climate", group: "Air Quality", location: "Cottage", color: false },
  { id: "media_player.home_theater", name: "Home Theater", section: "Reciever", group: "Media Player", location: "Rec Room", color: false },
  { id: "media_player.home_theater_2", name: "Home Theater", section: "Reciever", group: "Media Player", location: "Rec Room", color: false },
  { id: "media_player.home_theater_3", name: "Home Theater", section: "Reciever", group: "Media Player", location: "Rec Room", color: false },
  { id: "media_player.kitchen_speaker", name: "Kitchen Speaker", section: "Speaker", group: "Media Player", location: "Kitchen", color: false },
  { id: "media_player.kitchen_speaker_2", name: "Kitchen Speaker", section: "Speaker", group: "Media Player", location: "Kitchen", color: false },
  { id: "media_player.living_room_speaker", name: "Living Room Speaker", section: "Speaker", group: "Media Player", location: "Living Room", color: false },
  { id: "media_player.living_room_speaker_2", name: "Living Room Speaker", section: "Speaker", group: "Media Player", location: "Living Room", color: false },
  { id: "media_player.loft_google_tv", name: "Loft Google TV", section: "Google TV", group: "Media Player", location: "Loft", color: false },
  { id: "media_player.loft_google_tv_2", name: "Loft Google TV", section: "Google TV", group: "Media Player", location: "Loft", color: false },
  { id: "media_player.loft_speaker", name: "Loft speaker", section: "Speaker", group: "Media Player", location: "Loft", color: false },
  { id: "media_player.loft_speaker_2", name: "Loft speaker", section: "Speaker", group: "Media Player", location: "Loft", color: false },
  { id: "media_player.lucas_bedroom_speaker", name: "Lucas Bedroom speaker", section: "Speaker", group: "Media Player", location: "Lucas's Room", color: false },
  { id: "media_player.lucas_bedroom_speaker_2", name: "Lucas Bedroom speaker", section: "Speaker", group: "Media Player", location: "Lucas's Room_Speaker", color: false },
  { id: "media_player.master_bedroom_speaker", name: "Master Bedroom Speaker", section: "Speaker", group: "Media Player", location: "Master Bedroom", color: false },
  { id: "media_player.master_bedroom_speaker_2", name: "Master Bedroom Speaker", section: "Speaker", group: "Media Player", location: "Master Bedroom", color: false },
  { id: "media_player.rec_room_google_tv", name: "Rec Room Google TV", section: "Google TV", group: "Media Player", location: "Rec Room", color: false },
  { id: "media_player.rec_room_google_tv_2", name: "Rec Room Google TV", section: "Google TV", group: "Media Player", location: "Rec Room", color: false },
  { id: "media_player.rec_room_google_tv_3", name: "Rec Room Google TV", section: "Google TV", group: "Media Player", location: "Rec Room", color: false },
  { id: "media_player.sam_bedroom_speaker", name: "Sam Bedroom speaker", section: "Speaker", group: "Media Player", location: "Sam's Room", color: false },
  { id: "media_player.sam_bedroom_speaker_2", name: "Sam Bedroom speaker", section: "Speaker", group: "Media Player", location: "Sam's Room", color: false },
  { id: "select.loft_air_purifier_mode", name: "Loft Air Purifier Mode", section: "Climate", group: "Air Quality", location: "Loft Air Purifier", color: false },
  { id: "sensor.back_fan_bulb_1_status", name: "Back Fan Bulb 1 Status", section: "Lights", group: "Indoor Lights", location: "Back Fan Bulb", color: true },
  { id: "sensor.back_fan_bulb_2_status", name: "Back Fan Bulb 2 Status", section: "Lights", group: "Indoor Lights", location: "Back Fan Bulb", color: true },
  { id: "sensor.back_fan_bulb_3_status", name: "Back Fan Bulb 3 Status", section: "Lights", group: "Indoor Lights", location: "Back Fan Bulb", color: true },
  { id: "sensor.back_fan_bulb_4_status", name: "Back Fan Bulb 4 Status", section: "Lights", group: "Indoor Lights", location: "Back Fan Bulb", color: true },
  { id: "sensor.deck_lights_status", name: "Deck Lights Status", section: "Lights", group: "Outdoor Lights", location: "Deck Lights", color: true },
  { id: "sensor.deck_lights_status_2", name: "Deck Lights Status", section: "Lights", group: "Outdoor Lights", location: "Deck Lights", color: true },
  { id: "sensor.deck_stairs_status", name: "Deck Stairs Status", section: "Lights", group: "Outdoor Lights", location: "Deck Stairs", color: true },
  { id: "sensor.decoration_projector_status", name: "Decoration Projector Status", section: "Lights", group: "Outdoor Lights", location: "Decoration Projector", color: true },
  { id: "sensor.dog_closet_status", name: "Dog Closet Status", section: "Lights", group: "Indoor Lights", location: "Dog Closet", color: true },
  { id: "sensor.fireplace_light_status", name: "Fireplace Light Status", section: "Lights", group: "Indoor Lights", location: "Fireplace Light", color: true },
  { id: "sensor.firewalla_download_speed", name: "Firewalla Download speed", section: "Network Backend", group: "Firewalla", location: "Loft", color: false },
  { id: "sensor.firewalla_external_ip", name: "Firewalla External IP", section: "Network Backend", group: "Firewalla", location: "Loft", color: false },
  { id: "sensor.firewalla_upload_speed", name: "Firewalla Upload speed", section: "Network Backend", group: "Firewalla", location: "Loft", color: false },
  { id: "sensor.flood_lights_status", name: "Flood Lights Status", section: "Lights", group: "Indoor Lights", location: "Flood Lights", color: true },
  { id: "sensor.fridge_1_status", name: "Fridge 1 Status", section: "Lights", group: "Indoor Lights", location: "Fridge's Dge_1", color: true },
  { id: "sensor.fridge_2_status", name: "Fridge 2 Status", section: "Lights", group: "Indoor Lights", location: "Fridge's Dge_2", color: true },
  { id: "sensor.fridge_3_status", name: "Fridge 3 Status", section: "Lights", group: "Indoor Lights", location: "Fridge's Dge_3", color: true },
  { id: "sensor.front_fan_bulb_1_status", name: "Front Fan Bulb 1 Status", section: "Lights", group: "Indoor Lights", location: "Front Fan Bulb", color: true },
  { id: "sensor.front_fan_bulb_2_status", name: "Front Fan Bulb 2 Status", section: "Lights", group: "Indoor Lights", location: "Front Fan Bulb", color: true },
  { id: "sensor.front_fan_bulb_3_status", name: "Front Fan Bulb 3 Status", section: "Lights", group: "Indoor Lights", location: "Front Fan Bulb", color: true },
  { id: "sensor.front_fan_bulb_4_status", name: "Front Fan Bulb 4 Status", section: "Lights", group: "Indoor Lights", location: "Front Fan Bulb", color: true },
  { id: "sensor.front_porch_light_1_status", name: "Front Porch Light 1 Status", section: "Lights", group: "Indoor Lights", location: "Front Porch Light", color: true },
  { id: "sensor.front_porch_light_2_status", name: "Front Porch Light 2 Status", section: "Lights", group: "Indoor Lights", location: "Front Porch Light", color: true },
  { id: "sensor.frontyard_spotlights_status", name: "Frontyard Spotlights Status", section: "Lights", group: "Outdoor Lights", location: "Frontyard Spotlights", color: true },
  { id: "sensor.grill_lights_status", name: "Grill Lights Status", section: "Lights", group: "Outdoor Lights", location: "Grill Lights", color: true },
  { id: "sensor.h6076_173d_status", name: "Left Floor Lamp Status", section: "Lights", group: "Indoor Lights", location: "Left Floor Lamp", color: true },
  { id: "sensor.h7066_3337_status", name: "Spotlights Right Status", section: "Lights", group: "Outdoor Lights", location: "Spotlights Right", color: true },
  { id: "sensor.h7066_345b_status", name: "Spotlights Left Status", section: "Lights", group: "Outdoor Lights", location: "Spotlights Left", color: true },
  { id: "sensor.h70b5_7255_status", name: "Curtain Lights Status", section: "Lights", group: "Outdoor Lights", location: "Curtain Lights", color: true },
  { id: "sensor.hallway_hallway_fan_timer_timeout", name: "Hallway Fan timer timeout", section: "Climate", group: "Thermostat", location: "Hallway't _Fan_Timer", color: false },
  { id: "sensor.hallway_hallway_humidity", name: "Hallway Humidity", section: "Climate", group: "Thermostat", location: "Hallway'h ", color: false },
  { id: "sensor.hallway_hallway_temperature", name: "Hallway Temperature", section: "Climate", group: "Thermostat", location: "Hallway't ", color: false },
  { id: "sensor.living_room_therm_humidity", name: "Living Room therm Humidity", section: "Climate", group: "Air Quality", location: "Living Room therm", color: false },
  { id: "sensor.living_room_therm_status", name: "Living Room therm Status", section: "Climate", group: "Air Quality", location: "Living Room therm", color: false },
  { id: "sensor.living_room_therm_temperature", name: "Living Room therm Temperature", section: "Climate", group: "Air Quality", location: "Living Room therm", color: false },
  { id: "sensor.loft_air_monitor_airquality", name: "Loft Air Monitor airQuality", section: "Climate", group: "Air Quality", location: "Loft Air Monitor air", color: false },
  { id: "sensor.loft_air_monitor_humidity", name: "Loft Air Monitor Humidity", section: "Climate", group: "Air Quality", location: "Loft Air Monitor", color: false },
  { id: "sensor.loft_air_monitor_status", name: "Loft Air Monitor Status", section: "Climate", group: "Air Quality", location: "Loft Air Monitor", color: false },
  { id: "sensor.loft_air_monitor_temperature", name: "Loft Air Monitor Temperature", section: "Climate", group: "Air Quality", location: "Loft Air Monitor", color: false },
  { id: "sensor.loft_air_purifier_airquality", name: "Loft Air Purifier airQuality", section: "Climate", group: "Air Quality", location: "Loft Air Purifier air", color: false },
  { id: "sensor.loft_air_purifier_filterlifetime", name: "Loft Air Purifier filterLifeTime", section: "Climate", group: "Air Quality", location: "Loft Air Purifier filterLife", color: false },
  { id: "sensor.loft_air_purifier_status", name: "Loft Air Purifier Status", section: "Climate", group: "Air Quality", location: "Loft Air Purifier", color: false },
  { id: "sensor.lucas_light_status", name: "Lucas Light Status", section: "Lights", group: "", location: "Lucas Light", color: true },
  { id: "sensor.lucas_room_purifier_airquality", name: "Lucas Room Purifier airQuality", section: "Climate", group: "Air Quality", location: "Lucas Room Purifier air", color: false },
  { id: "sensor.lucas_room_purifier_filterlifetime", name: "Lucas Room Purifier filterLifeTime", section: "Climate", group: "Air Quality", location: "Lucas Room Purifier filterLife", color: false },
  { id: "sensor.lucas_room_purifier_status", name: "Lucas Room Purifier Status", section: "Climate", group: "Air Quality", location: "Lucas Room Purifier", color: false },
  { id: "sensor.lucqs_room_air_monitor_airquality", name: "Lucas Room Air Monitor airQuality", section: "Climate", group: "Air Quality", location: "Lucas Room Air Monitor air", color: false },
  { id: "sensor.lucqs_room_air_monitor_humidity", name: "Lucas Room Air Monitor Humidity", section: "Climate", group: "Air Quality", location: "Lucas Room Air Monitor", color: false },
  { id: "sensor.lucqs_room_air_monitor_status", name: "Lucas Room Air Monitor Status", section: "Climate", group: "Air Quality", location: "Lucas Room Air Monitor", color: false },
  { id: "sensor.lucqs_room_air_monitor_temperature", name: "Lucas Room Air Monitor Temperature", section: "Climate", group: "Air Quality", location: "Lucas Room Air Monitor", color: false },
  { id: "sensor.pc_smart_plug_status", name: "PC Smart Plug Status", section: "Power", group: "Power", location: "PC Smart Plug", color: false },
  { id: "sensor.porch_light_1_status", name: "Porch Light 1 Status", section: "Lights", group: "Outdoor Lights", location: "Porch Light", color: true },
  { id: "sensor.porch_light_2_status", name: "Porch Light 2 Status", section: "Lights", group: "Outdoor Lights", location: "Porch Light", color: true },
  { id: "sensor.porch_light_4_status", name: "Porch Light 4 Status", section: "Lights", group: "Outdoor Lights", location: "Porch Light", color: true },
  { id: "sensor.porch_light_5_status", name: "Porch Light 5 Status", section: "Lights", group: "Outdoor Lights", location: "Porch Light", color: true },
  { id: "sensor.porch_light_7_status", name: "Porch Light 7 Status", section: "Lights", group: "Outdoor Lights", location: "Porch Light", color: true },
  { id: "sensor.porch_light_8_status", name: "Porch Light 8 Status", section: "Lights", group: "Outdoor Lights", location: "Porch Light", color: true },
  { id: "sensor.porch_lights_status", name: "Porch Lights Status", section: "Lights", group: "Outdoor Lights", location: "Porch Lights", color: true },
  { id: "sensor.rec_room_air_monitor_airquality", name: "Rec Room AIr Monitor airQuality", section: "Climate", group: "Air Quality", location: "Rec Room AIr Monitor air", color: false },
  { id: "sensor.rec_room_air_monitor_humidity", name: "Rec Room AIr Monitor Humidity", section: "Climate", group: "Air Quality", location: "Rec Room AIr Monitor", color: false },
  { id: "sensor.rec_room_air_monitor_status", name: "Rec Room AIr Monitor Status", section: "Climate", group: "Air Quality", location: "Rec Room AIr Monitor", color: false },
  { id: "sensor.rec_room_air_monitor_temperature", name: "Rec Room AIr Monitor Temperature", section: "Climate", group: "Air Quality", location: "Rec Room AIr Monitor", color: false },
  { id: "sensor.rec_room_air_purifier_airquality", name: "Rec Room Air Purifier airQuality", section: "Climate", group: "Air Quality", location: "Rec Room Air Purifier air", color: false },
  { id: "sensor.rec_room_air_purifier_filterlifetime", name: "Rec Room Air Purifier filterLifeTime", section: "Climate", group: "Air Quality", location: "Rec Room Air Purifier filterLife", color: false },
  { id: "sensor.rec_room_air_purifier_status", name: "Rec Room Air Purifier Status", section: "Climate", group: "Air Quality", location: "Rec Room Air Purifier", color: false },
  { id: "sensor.rec_room_thermometer_humidity", name: "Rec Room thermometer Humidity", section: "Climate", group: "Air Quality", location: "Rec Room thermometer", color: false },
  { id: "sensor.rec_room_thermometer_humidity_2", name: "Rec Room thermometer Humidity", section: "Climate", group: "Air Quality", location: "Rec Room thermometer", color: false },
  { id: "sensor.rec_room_thermometer_status", name: "Rec Room thermometer Status", section: "Climate", group: "Air Quality", location: "Rec Room thermometer", color: false },
  { id: "sensor.rec_room_thermometer_status_2", name: "Rec Room thermometer Status", section: "Climate", group: "Air Quality", location: "Rec Room thermometer", color: false },
  { id: "sensor.rec_room_thermometer_temperature", name: "Rec Room thermometer Temperature", section: "Climate", group: "Air Quality", location: "Rec Room thermometer", color: false },
  { id: "sensor.rec_room_thermometer_temperature_2", name: "Rec Room thermometer Temperature", section: "Climate", group: "Air Quality", location: "Rec Room thermometer", color: false },
  { id: "sensor.rec_room_wall_lighting_status", name: "Rec Room Lights Status", section: "Lights", group: "Indoor Lights", location: "Rec Room Lights", color: true },
  { id: "sensor.right_floor_lamp_status", name: "Right Floor Lamp Status", section: "Lights", group: "Indoor Lights", location: "Right Floor Lamp", color: true },
  { id: "sensor.sam_s_air_monitor_airquality", name: "Sam's AIr Monitor airQuality", section: "Climate", group: "Air Quality", location: "Sam's AIr Monitor air", color: false },
  { id: "sensor.sam_s_air_monitor_humidity", name: "Sam's AIr Monitor Humidity", section: "Climate", group: "Air Quality", location: "Sam's AIr Monitor", color: false },
  { id: "sensor.sam_s_air_monitor_status", name: "Sam's AIr Monitor Status", section: "Climate", group: "Air Quality", location: "Sam's AIr Monitor", color: false },
  { id: "sensor.sam_s_air_monitor_temperature", name: "Sam's AIr Monitor Temperature", section: "Climate", group: "Air Quality", location: "Sam's AIr Monitor", color: false },
  { id: "sensor.sam_s_air_purifier_airquality", name: "Sam's Air Purifier airQuality", section: "Climate", group: "Air Quality", location: "Sam's Air Purifier air", color: false },
  { id: "sensor.sam_s_air_purifier_filterlifetime", name: "Sam's Air Purifier filterLifeTime", section: "Climate", group: "Air Quality", location: "Sam's Air Purifier filterLife", color: false },
  { id: "sensor.sam_s_air_purifier_status", name: "Sam's Air Purifier Status", section: "Climate", group: "Air Quality", location: "Sam's Air Purifier", color: false },
  { id: "sensor.star_light_projector_status", name: "Star Light Projector Status", section: "Lights", group: "Indoor Lights", location: "Star Light Projector", color: true },
  { id: "sensor.tyler_s_air_monitor_airquality", name: "Tyler's AIr Monitor airQuality", section: "Climate", group: "Air Quality", location: "Tyler's AIr Monitor air", color: false },
  { id: "sensor.tyler_s_air_monitor_humidity", name: "Tyler's AIr Monitor Humidity", section: "Climate", group: "Air Quality", location: "Tyler's AIr Monitor", color: false },
  { id: "sensor.tyler_s_air_monitor_status", name: "Tyler's AIr Monitor Status", section: "Climate", group: "Air Quality", location: "Tyler's AIr Monitor", color: false },
  { id: "sensor.tyler_s_air_monitor_temperature", name: "Tyler's AIr Monitor Temperature", section: "Climate", group: "Air Quality", location: "Tyler's AIr Monitor", color: false },
  { id: "sensor.tyler_s_air_purifier_airquality", name: "Tyler's Air Purifier airQuality", section: "Climate", group: "Air Quality", location: "Tyler's Air Purifier air", color: false },
  { id: "sensor.tyler_s_air_purifier_filterlifetime", name: "Tyler's Air Purifier filterLifeTime", section: "Climate", group: "Air Quality", location: "Tyler's Air Purifier filterLife", color: false },
  { id: "sensor.tyler_s_air_purifier_status", name: "Tyler's Air Purifier Status", section: "Climate", group: "Air Quality", location: "Tyler's Air Purifier", color: false },
  { id: "switch.back_fan_bulb_1_power_switch", name: "Back Fan Bulb 1 Power Switch", section: "Lights", group: "Indoor Lights", location: "Back Fan Bulb 1 Power", color: true },
  { id: "switch.back_fan_bulb_2_power_switch", name: "Back Fan Bulb 2 Power Switch", section: "Lights", group: "Indoor Lights", location: "Back Fan Bulb 2 Power", color: true },
  { id: "switch.back_fan_bulb_3_power_switch", name: "Back Fan Bulb 3 Power Switch", section: "Lights", group: "Indoor Lights", location: "Back Fan Bulb 3 Power", color: true },
  { id: "switch.back_fan_bulb_4_power_switch", name: "Back Fan Bulb 4 Power Switch", section: "Lights", group: "Indoor Lights", location: "Back Fan Bulb 4 Power", color: true },
  { id: "switch.curtain_lights_power_switch", name: "Curtain Lights Power Switch", section: "Lights", group: "Outdoor Lights", location: "Curtain Lights Power", color: true },
  { id: "switch.deck_lights_gradient_toggle", name: "Deck Lights Gradient Toggle", section: "Lights", group: "Outdoor Lights", location: "Deck Lights Gradient", color: true },
  { id: "switch.deck_lights_power_switch", name: "Deck Lights Power Switch", section: "Lights", group: "Outdoor Lights", location: "Deck Lights Power", color: true },
  { id: "switch.deck_lights_power_switch_2", name: "Deck Lights Power Switch", section: "Lights", group: "Outdoor Lights", location: "Deck Lights Power", color: true },
  { id: "switch.deck_stairs_power_switch", name: "Deck Stairs Power Switch", section: "Lights", group: "Outdoor Lights", location: "Deck Stairs Power", color: true },
  { id: "switch.decoration_projector_power_switch", name: "Decoration Projector Power Switch", section: "Lights", group: "Outdoor Lights", location: "Decoration Projector Power", color: true },
  { id: "switch.dog_closet_power_switch", name: "Dog Closet Power Switch", section: "Lights", group: "Indoor Lights", location: "Dog Closet Power", color: true },
  { id: "switch.fireplace_light_power_switch", name: "Fireplace Light Power Switch", section: "Lights", group: "Indoor Lights", location: "Fireplace Light Power", color: true },
  { id: "switch.flood_lights_power_switch", name: "Flood Lights Power Switch", section: "Lights", group: "Indoor Lights", location: "Flood Lights Power", color: true },
  { id: "switch.floor_lamp_scenes_power_switch", name: "Floor lamp scenes Power Switch", section: "Lights", group: "Indoor Lights", location: "Floor lamp scenes Power", color: true },
  { id: "switch.fridge_1_power_switch", name: "Fridge 1 Power Switch", section: "Lights", group: "Indoor Lights", location: "Fridge 1 Power", color: true },
  { id: "switch.fridge_2_power_switch", name: "Fridge 2 Power Switch", section: "Lights", group: "Indoor Lights", location: "Fridge 2 Power", color: true },
  { id: "switch.fridge_3_power_switch", name: "Fridge 3 Power Switch", section: "Lights", group: "Indoor Lights", location: "Fridge 3 Power", color: true },
  { id: "switch.front_fan_bulb_1_power_switch", name: "Front Fan Bulb 1 Power Switch", section: "Lights", group: "Indoor Lights", location: "Front Fan Bulb 1 Power", color: true },
  { id: "switch.front_fan_bulb_2_power_switch", name: "Front Fan Bulb 2 Power Switch", section: "Lights", group: "Indoor Lights", location: "Front Fan Bulb 2 Power", color: true },
  { id: "switch.front_fan_bulb_3_power_switch", name: "Front Fan Bulb 3 Power Switch", section: "Lights", group: "Indoor Lights", location: "Front Fan Bulb 3 Power", color: true },
  { id: "switch.front_fan_bulb_4_power_switch", name: "Front Fan Bulb 4 Power Switch", section: "Lights", group: "Indoor Lights", location: "Front Fan Bulb 4 Power", color: true },
  { id: "switch.front_porch_light_1_power_switch", name: "Front Porch Light 1 Power Switch", section: "Lights", group: "Outdoor Lights", location: "Front Porch Light 1 Power", color: true },
  { id: "switch.front_porch_light_2_power_switch", name: "Front Porch Light 2 Power Switch", section: "Lights", group: "Outdoor Lights", location: "Front Porch Light 2 Power", color: true },
  { id: "switch.frontyard_spotlights_power_switch", name: "Frontyard Spotlights Power Switch", section: "Lights", group: "Outdoor Lights", location: "Frontyard Spotlights Power", color: true },
  { id: "switch.grill_lights_power_switch", name: "Grill Lights Power Switch", section: "Lights", group: "Outdoor Lights", location: "Grill Lights Power", color: true },
  { id: "switch.left_floor_lamp_dream_view_toggle", name: "Left Floor Lamp Dream View Toggle", section: "Lights", group: "Indoor Lights", location: "Left Floor Lamp Dream View", color: true },
  { id: "switch.left_floor_lamp_gradient_toggle", name: "Left Floor Lamp Gradient Toggle", section: "Lights", group: "Indoor Lights", location: "Left Floor Lamp Gradient", color: true },
  { id: "switch.left_floor_lamp_power_switch", name: "Left Floor Lamp Power Switch", section: "Lights", group: "Indoor Lights", location: "Left Floor Lamp Power", color: true },
  { id: "switch.loft_air_purifier_power_switch", name: "Loft Air Purifier Power Switch", section: "Climate", group: "Air Quality", location: "Loft Air Purifier Power", color: false },
  { id: "switch.lucas_light_power_switch", name: "Lucas Light Power Switch", section: "Climate", group: "Air Quality", location: "Lucas Light Power", color: false },
  { id: "switch.lucas_room_purifier_power_switch", name: "Lucas Room Purifier Power Switch", section: "Climate", group: "Air Quality", location: "Lucas Room Purifier Power", color: false },
  { id: "switch.pc_smart_plug_power_switch", name: "PC Smart Plug Power Switch", section: "Power", group: "Power", location: "PC Smart Plug Power", color: false },
  { id: "switch.porch_light_1_power_switch", name: "Porch Light 1 Power Switch", section: "Lights", group: "Outdoor Lights", location: "Porch Light 1 Power", color: true },
  { id: "switch.porch_light_2_power_switch", name: "Porch Light 2 Power Switch", section: "Lights", group: "Outdoor Lights", location: "Porch Light 2 Power", color: true },
  { id: "switch.porch_light_4_power_switch", name: "Porch Light 4 Power Switch", section: "Lights", group: "Outdoor Lights", location: "Porch Light 4 Power", color: true },
  { id: "switch.porch_light_5_power_switch", name: "Porch Light 5 Power Switch", section: "Lights", group: "Outdoor Lights", location: "Porch Light 5 Power", color: true },
  { id: "switch.porch_light_7_power_switch", name: "Porch Light 7 Power Switch", section: "Lights", group: "Outdoor Lights", location: "Porch Light 7 Power", color: true },
  { id: "switch.porch_light_8_power_switch", name: "Porch Light 8 Power Switch", section: "Lights", group: "Outdoor Lights", location: "Porch Light 8 Power", color: true },
  { id: "switch.porch_lights_power_switch", name: "Porch Lights Power Switch", section: "Lights", group: "Outdoor Lights", location: "Porch Lights Power", color: true },
  { id: "switch.rec_room_air_purifier_power_switch", name: "Rec Room Air Purifier Power Switch", section: "Climate", group: "Air Quality", location: "Rec Room Air Purifier Power", color: false },
  { id: "switch.rec_room_fan_lighting_power_switch", name: "Rec Room Fan Lighting Power Switch", section: "Climate", group: "Air Quality", location: "Rec Room Fan Lighting Power", color: false },
  { id: "switch.rec_room_power_switch", name: "Rec Room Power Switch", section: "Lights", group: "Indoor Lights", location: "Rec Room Power", color: true },
  { id: "switch.rec_room_wall_lighting_power_switch", name: "Rec Room Lights Power Switch", section: "Lights", group: "Indoor Lights", location: "Rec Room Lights Power", color: true },
  { id: "switch.sam_s_air_purifier_power_switch", name: "Sam's Air Purifier Power Switch", section: "Climate", group: "Air Quality", location: "Sam's Air Purifier Power", color: false },
  { id: "switch.spotlights_left_power_switch", name: "Spotlights Left Power Switch", section: "Lights", group: "Outdoor Lights", location: "Spotlights Left Power", color: true },
  { id: "switch.spotlights_right_gradient_toggle", name: "Spotlights Right Gradient Toggle", section: "Lights", group: "Outdoor Lights", location: "Spotlights Right Gradient", color: true },
  { id: "switch.spotlights_right_power_switch", name: "Spotlights Right Power Switch", section: "Lights", group: "Outdoor Lights", location: "Spotlights Right Power", color: true },
  { id: "switch.star_light_projector_power_switch", name: "Star Light Projector Power Switch", section: "Lights", group: "Indoor Lights", location: "Star Light Projector Power", color: true },
  { id: "switch.tyler_s_air_purifier_nightlight_toggle", name: "Tyler's Air Purifier Nightlight Toggle", section: "Climate", group: "Air Quality", location: "Tyler's Air Purifier Nightlight", color: false },
  { id: "switch.tyler_s_air_purifier_power_switch", name: "Tyler's Air Purifier Power Switch", section: "Climate", group: "Air Quality", location: "Tyler's Air Purifier Power", color: false },
];