services:
  - type: web
    name: nexus
    runtime: node
    plan: starter
    buildCommand: "cd client && npm install && npm run build && cd ../server && npm install"
    startCommand: "cd server && node index.js"
    envVars:
      - key: HA_URL
        sync: false
      - key: HA_TOKEN
        sync: false
      - key: GOVEE_API_KEY
        sync: false
